#Configuracion
#Sun May 31 17:45:54 MST 2026
registration.window.height=671
registration.window.width=1240
registration.window.x=158
registration.window.y=131
users.export.pdf=C\:\\Users\\ponch
vehiculos.export.pdf=C\:\\Users\\ponch
